### ISSUE TITLE
登录的时候报错

### ISSUE THREAD

**Issue by zhaoml529** [ZevenFang/zevencourse#4]
严重: Servlet.service() for servlet [dispatcher] in context with path [] threw exception [Request processing failed; nested exception is io.jsonwebtoken.SignatureException: Unable to obtain JCA MAC algorithm 'HmacSHA256': Algorithm HmacSHA256 not available] with root cause
java.security.NoSuchAlgorithmException: Algorithm HmacSHA256 not available
	at javax.crypto.Mac.getInstance(Mac.java:176)
	at io.jsonwebtoken.impl.crypto.MacSigner.doGetMacInstance(MacSigner.java:64)
	at io.jsonwebtoken.impl.crypto.MacSigner.getMacInstance(MacSigner.java:53)
	at io.jsonwebtoken.impl.crypto.MacSigner.sign(MacSigner.java:47)
	at io.jsonwebtoken.impl.crypto.DefaultJwtSigner.sign(DefaultJwtSigner.java:45)
	at io.jsonwebtoken.impl.DefaultJwtBuilder.compact(DefaultJwtBuilder.java:323)
	at com.zeven.course.action.AccessAction.signin(AccessAction.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
...

请问你的JDK是1.7 还是1.8？

**Comment by ZevenFang** [comment]
之前用1.7，后来换到1.8的环境，不过两个版本应该都可以运行的

**Comment by ZevenFang** [comment]
我这边可以正常登陆，能不能给出更详细的信息
在AccessAction.java第68行断点，给出一些变量值

**Comment by zhaoml529** [comment]
没啥变量值Jwts.builder().setClaims(claims)，claims值是{id=1, name=管理员, role=admin}，直接就从这行报错。

**Comment by zhaoml529** [comment]
是不是和环境有关，我也没换jdk，不太清楚。

**Comment by zhaoml529** [comment]
JDK问题 换了个版本好了

**Comment by ZevenFang** [comment]
这应该是由于我使用了jjwt_6.0版本导致的，
具体的issue可以参考：https://github.com/jwtk/jjwt/issues/73
